services:
  nginx:
    build: .
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro,z
      - ./conf.d:/etc/nginx/conf.d:z
    networks:
      - proxy-net
    restart: always

networks:
  proxy-net:
    external: true
